# Generated by Django 4.1 on 2022-08-16 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='address',
            table='address',
        ),
        migrations.AlterModelTable(
            name='merchant',
            table='merchant',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
